// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeL1Fc_uhPqUwQ10aioQbjGccf0d1BLag',
    appId: '1:970541325537:web:25d21a8b57e248b366eba0',
    messagingSenderId: '970541325537',
    projectId: 'grabber-f698e',
    authDomain: 'grabber-f698e.firebaseapp.com',
    storageBucket: 'grabber-f698e.appspot.com',
    measurementId: 'G-Y81G0EWWYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKh8BpP29C63wiNXsJxft1fvfJQOuFg44',
    appId: '1:970541325537:android:479eed2952136b5966eba0',
    messagingSenderId: '970541325537',
    projectId: 'grabber-f698e',
    storageBucket: 'grabber-f698e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwvlGZ-1-RYr07YwoDWCtffvgooIBC-A8',
    appId: '1:970541325537:ios:2eaefb83c056817f66eba0',
    messagingSenderId: '970541325537',
    projectId: 'grabber-f698e',
    storageBucket: 'grabber-f698e.appspot.com',
    iosClientId: '970541325537-f93p2c848roj4npo8m75djv32f3ph3qq.apps.googleusercontent.com',
    iosBundleId: 'com.example.grabber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwvlGZ-1-RYr07YwoDWCtffvgooIBC-A8',
    appId: '1:970541325537:ios:2eaefb83c056817f66eba0',
    messagingSenderId: '970541325537',
    projectId: 'grabber-f698e',
    storageBucket: 'grabber-f698e.appspot.com',
    iosClientId: '970541325537-f93p2c848roj4npo8m75djv32f3ph3qq.apps.googleusercontent.com',
    iosBundleId: 'com.example.grabber',
  );
}
